### ISSUE TITLE
Create single file distribution to be used in browser

### ISSUE THREAD

**Issue by chhantyal** [laurent22/joplin-turndown-plugin-gfm#3]
Would be nice to have single file which can be easily used in browsers.

Btw, thanks for this fork. I am looking to fix issue related to tables without table head

**Comment by laurent22** [comment]
What do you mean by "single fine"?

**Comment by chhantyal** [comment]
Sorry, that was typo. I mean to say 'single file' 🤦‍♂

**Comment by chhantyal** [comment]
Never mind, I only needed tables.js and made a fork.
